### ISSUE TITLE
Unable to load local path returned by Samsung Galaxy S4

### ISSUE THREAD

**Issue by marcoRS** [Ink/filepicker-android#53]
We're having an issue where we are unable to load a local image path returned from a galaxy s4 phone when a photo is taken from the camera. The image url is returned but the local path appears to be invalid. 

Have you guys seen any particular bugs with respect to samsung devices? Maybe its related to this? https://github.com/square/picasso/issues/539

**Comment by maciejwitowski** [comment]
I've tested again and it seems to work on Galaxy S4. I think it may have been connected to S4 software version.
I'll close the issue for now, but feel free to open it if you ever encounter it in the future.

**Comment by ABBESFadwa** [comment]
i steal have the same problème but not just on S4 , even on Alcatel oneTouch and everShine.
have any one any answer plz?
