### ISSUE TITLE
Dropbox Support

### ISSUE THREAD

**Issue by marcoRS** [Ink/filepicker-android#57]
Hello, Dropbox does not appear to be working even after following these directions: http://filepicker.com/blog/working-with-filepicker/changes-user-uploads-dropbox/

When I choose an image from dropbox I am sent back to the original App. There is no indication that upload ever happened or failed.

**Comment by maciejwitowski** [comment]
Hi, 

localPath is shown only for locally stored files (when user uses Gallery or Camera), not for cloud services.

Best,
