### ISSUE TITLE
Filepicker Api setAppName

### ISSUE THREAD

**Issue by marcoRS** [Ink/filepicker-android#59]
Currently Filepicker.setAppName() has no effect. Have you considered allowing a user to put a App name through the calling intent? Setting an app name through a static method runs the risk of the name being GC'd.

**Comment by maciejwitowski** [comment]
Fixed in 3.7.3.

**Comment by marcoRS** [comment]
Passing as a static field is safe only if you assume that the user will be quickly be in/out of FilePicker. If for some reason the last view the user sees is the FilePicker and the user presses home or does something else and the system kills the app, if the user then goes back to the app the static field will be GC'd since the system is creating the app.
