### ISSUE TITLE
Configuration Changes

### ISSUE THREAD

**Issue by marcoRS** [Ink/filepicker-android#62]
When logging into a service the first time say for example Flickr, when on the login page if the user rotates the device the login page disappears and you get a menu option that says "Logout" but the user has not logged in.  This also happens with other configuration changes such as when switching languages. 

Also if a user has already logged into another service before Flickr, if the device is rotated while on the login, the title reads Flickr but the other services' files get displayed. 

![flickr-login](https://cloud.githubusercontent.com/assets/507510/5762728/1bca94e6-9c99-11e4-8aea-17cd93b189a0.png)

![flickr-login-rotate](https://cloud.githubusercontent.com/assets/507510/5762730/206273ac-9c99-11e4-80bc-8f8729120dfa.png)

**Comment by maciejwitowski** [comment]
Fixed in version 3.8.1
