### ISSUE TITLE
Unable to run the Sample application

### ISSUE THREAD

**Issue by vusarath** [Ink/filepicker-android#67]
Hello,

I am using this filepicker-android.

I am get this error at line startActivityForResult(intent, Filepicker.REQUEST_CODE_GETFILE);
android.content.ActivityNotFoundException: Unable to find explicit activity class {com.filemanager/io.filepicker.Filepicker}; have you declared this activity in your AndroidManifest.xml?

i followed all the steps given in this link https://github.com/Ink/filepicker-android

Is their any thing else which i am missing

**Comment by maciejwitowski** [comment]
Hi,

Filepicker activity is declared in library's AndroidManifest file so it should work as soon as you add Filepicker dependency in your Gradle file:

```groovy
compile "io.filepicker:filepicker-android:3.8.2"
```
Does your problem still occur?

**Comment by vusarath** [comment]
I am working with eclipse .I am able to solve that problem.
But now i am unable to open drive or dropbox
