### ISSUE TITLE
Open Camera method crashes when no Camera

### ISSUE THREAD

**Issue by marcoRS** [Ink/filepicker-android#69]
Some devices do not have a camera activity that would handle the intent here: 

https://github.com/Ink/filepicker-android/blob/master/filepicker-library/src/io/filepicker/FilePicker.java#L523

Using a try catch with a ActivityNotFoundException would be nicer then having filepicker crash.

**Comment by maciejwitowski** [comment]
Thanks for the catch, I've fixed in in 3.8.3.
