### ISSUE TITLE
Gradle build error

### ISSUE THREAD

**Issue by xata1988** [Ink/filepicker-android#72]
Hi, I'm adding library like this

    dependencies {
        compile fileTree(dir: 'libs', include: ['*.jar'])
        compile 'com.github.amlcurran.showcaseview:library:5.0.0'
        compile "io.filepicker:filepicker-android:3.8.3"
    }

and I got next gradle error

Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.android.support:support-v4:21.0.2.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/support-v4/21.0.2/support-v4-21.0.2.pom
         https://jcenter.bintray.com/com/android/support/support-v4/21.0.2/support-v4-21.0.2.jar
         file:/C:/Program Files (x86)/Android/android-studio/sdk/extras/android/m2repository/com/android/support/support-v4/21.0.2/support-v4-21.0.2.pom
         file:/C:/Program Files (x86)/Android/android-studio/sdk/extras/android/m2repository/com/android/support/support-v4/21.0.2/support-v4-21.0.2.jar
         file:/C:/Program Files (x86)/Android/android-studio/sdk/extras/google/m2repository/com/android/support/support-v4/21.0.2/support-v4-21.0.2.pom
         file:/C:/Program Files (x86)/Android/android-studio/sdk/extras/google/m2repository/com/android/support/support-v4/21.0.2/support-v4-21.0.2.jar
     Required by:
         AClock:app:unspecified > io.filepicker:filepicker-android:3.8.3

**Comment by maciejwitowski** [comment]
Do you have Android Support Repository installed? It seems like you have a problem with this.

This may help: http://stackoverflow.com/questions/19958213/how-to-add-android-support-repository-to-android-studio

**Comment by xata1988** [comment]
This solved the problem. Thanks.
