### ISSUE TITLE
Unnecessary service selection

### ISSUE THREAD

**Issue by jamestope** [Ink/filepicker-android#78]
If you request a File Pick specifying only one service, you still have to pick that service from a list of one before you see your files. It would be a better user experience to go straight to the auth or files view in this case.

thanks

**Comment by dbaq** [comment]
:+1: 

I am currently encountering the use case. @maciejwitowski, can you take a look please?

thanks in advance

**Comment by maciejwitowski** [comment]
I'll will try to look at it in the next few days.
Cheers,

**Comment by maciejwitowski** [comment]
Finally I've added this feature. Available from 3.8.17
