### ISSUE TITLE
Use native app instead of web apps

### ISSUE THREAD

**Issue by dbaq** [Ink/filepicker-android#82]
Hi,

It would be great to use the native apps if they are installed on the device instead of asking the user to enter his credentials on the web app. I am talking about dropbox, facebook and all this kind of services.

Any thoughts on that?

**Comment by maciejwitowski** [comment]
Hi,

Thanks for the suggestion, however we are not going to use native apps here.

One of the benefits of the filepicker library is a possibility to browse the files from different services without jumping between apps. It's a bit of burden when you need to enter login/password, but we believe the overall experience is better this way.

The other reason is that this change would require a lot of changes in technical part of cooperation between mobile app and filepicker api.

Cheers
